### PR TITLE
Factor out common constraint in type signatures.

### PR DESCRIPTION
**Pull request by agam**

### CODE REVIEW

**Review by aviaviavi — COMMENTED** [review]
thanks for this PR @agam! neat, i wasn't familiar with RankNTypes

is there any particular reason the signature for `mineBlock` wasn't updated? just wanted to check if that was on purpose or not.

**Comment by agam** [comment]
Yes, I initially thought that was similar too, but squinting closely, the return type doesn't match the `m type` pattern of the previous two (i.e. the first is `m [Block]` and the second is `m Block`, but the third is `String -> m Block`).

**Comment by aviaviavi** [comment]
ah right i see. cool well looks good, thanks again!

**Comment by agam** [comment]
Well, thanks for writing up this neat implementation, very instructive!

**Pull request merged**
